{% set name = "matbench" %}
{% set version = "0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/materialsproject/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 6143472780920a9040f6a222f86e93da42e2fee075e426d598159e8405cfd9b4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matminer ==0.7.4
    - monty ==2022.4.26
    - python >=3.6
    - scikit-learn ==1.0.1
    - scipy ==1.7.3

test:
  imports:
    - matbench
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/materialsproject/matbench
  summary: a machine learning benchmark for materials science
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
